# Generated by Django 3.2.8 on 2021-10-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug-имя')),
                ('name', models.TextField(db_index=True, max_length=64, unique=True, verbose_name='Название вселенной')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание вселенной')),
                ('short_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Краткое описание вселенной')),
            ],
            options={
                'verbose_name': 'вселенная',
                'verbose_name_plural': 'вселенные',
                'ordering': ['name'],
            },
        ),
    ]
