"""
Django settings for dl_portal project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vtxz6ngc-6^q^*y9*8tp0q9f15jb99o57yc9-7-v!uj3+b6i_2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'debug_toolbar',
    'ckeditor',
    'ckeditor_uploader',

    'universes.apps.UniversesConfig',
    'users.apps.UsersConfig',
    'posts.apps.PostsConfig',
    'pages.apps.PagesConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'dl_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dl_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'  # Url prefix for static files
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # Real dir with all static
# List of dirs with static that should be collected (app's static not to be specified there)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'dl_portal/static'),
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INTERNAL_IPS = [
    '127.0.0.1',
]

AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = [
    'users.backends.UsersAuthBackend'
]

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_FILENAME_GENERATOR = 'dl_portal.utils.get_cke_filename'
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'skin': 'moono-lisa',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Source', '-', 'Preview']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Blockquote', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl']},
            '/',
            {'name': 'basicstyles',
             'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat']},
            {'name': 'styles', 'items': ['Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'links', 'items': ['Link', 'Unlink']},
            {'name': 'insert',
             'items': ['Image', 'Table', 'HorizontalRule']},
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
        # 'height': 300,
        # 'width': '130%',
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage', # the upload image feature
            # your extra plugins here
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            # 'devtools',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath'
        ]),
    }
}

ALLOWED_TAGS = [
    # '<!DOCTYPE>',
    # '<!-- -->',
    '<a>',
    '<abbr>',
    '<acronym>',
    # '<address>',
    # '<applet>',
    # '<area>',
    # '<article>',
    # '<aside>',
    # '<audio>',
    '<b>',
    # '<base>',
    # '<basefont>',
    # '<bdi>',
    # '<bdo>',
    # '<bgsound>',
    '<blockquote>',
    '<big>',
    # '<body>',
    # '<blink>',
    '<br>',
    # '<button>',
    # '<canvas>',
    # '<caption>',
    '<center>',
    # '<cite>',
    '<code>',
    # '<col>',
    # '<colgroup>',
    # '<command>',
    # '<comment>',
    # '<datalist>',
    # '<dd>',
    # '<del>',
    # '<details>',
    # '<dfn>',
    # '<dir>',
    '<div>',
    # '<dl>',
    # '<dt>',
    '<em>',
    # '<embed>',
    # '<fieldset>',
    # '<figcaption>',
    # '<figure>',
    '<font>',
    # '<form>',
    # '<footer>',
    # '<frame>',
    # '<frameset>',
    '<h1>',
    '<h2>',
    '<h3>',
    '<h4>',
    '<h5>',
    '<h6>',
    # '<head>',
    # '<header>',
    # '<hgroup>',
    '<hr>',
    # '<html>',
    '<i>',
    # '<iframe>',
    # '<img>',
    # '<input>',
    # '<ins>',
    # '<isindex>',
    # '<kbd>',
    # '<keygen>',
    '<label>',
    # '<legend>',
    '<li>',
    # '<link>',
    # '<main>',
    # '<map>',
    # '<marquee>',
    # '<mark>',
    # '<menu>',
    # '<meta>',
    # '<meter>',
    # '<nav>',
    # '<nobr>',
    # '<noembed>',
    # '<noframes>',
    # '<noscript>',
    # '<object>',
    '<ol>',
    # '<optgroup>',
    # '<option>',
    # '<output>',
    '<p>',
    # '<param>',
    '<plaintext>',
    # '<pre>',
    # '<progress>',
    '<q>',
    # '<rp>',
    # '<rt>',
    # '<ruby>',
    '<s>',
    # '<samp>',
    # '<script>',
    # '<section>',
    # '<select>',
    '<small>',
    '<span>',
    # '<source>',
    '<strike>',
    '<strong>',
    # '<style>',
    # '<sub>',
    # '<summary>',
    # '<sup>',
    '<table>',
    # '<tbody>',
    '<td>',
    # '<textarea>',
    # '<tfoot>',
    # '<th>',
    # '<thead>',
    # '<time>',
    # '<title>',
    '<tr>',
    # '<tt>',
    '<u>',
    '<ul>',
    # '<var>',
    # '<video>',
    # '<wbr>',
    # '<xmp>',
]
